### PR TITLE
Initial (very rough) cmake infrastructure

### PR DESCRIPTION
**Pull request by Barthelemy**
Only Common is compiled. See the notes in README about questions it raised.

### CODE REVIEW

**Comment by Barthelemy** [comment]
A few points / questions to be answered : 
- Include prefixed with module name ? ie. "include Common/Bar.h" instead of "include Bar.h" ?
  
  I think that it is necessary as we use namespaces (it could clash on the name of headers).
- Is the "include" directory only for public headers or all headers ? 
- Using the o2_target_link_bucket is ok for libraries. For executables the problem is that we might want to also link against the lbirary produced in the same module.
- Where do we call "find_package" ? along with the bucket definitions ?

**Comment by ktf** [comment]
My personal preferences:
- include Common/Bar.h
- only public headers
- IMHO executables should always belong to the same bucket + the sub-package library
- sounds like a good idea.

**Comment by Barthelemy** [comment]
Good. 
- ok
- ok -> need to add some headers in the src to show this
- We have to see how to enforce it in a simple way
- ok

**Comment by Barthelemy** [comment]
CMake used in all modules but DataFormats (I leave it to you, I am not sure what to do here). In the README there is a TODO list (I did not have time to create issues) : 
- add a non public header that is in src
- DataFormats cmake
- doxygen example
- test example
- enforce that "executables should always belong to the same bucket + the sub-package library" ?
- script to create new module (in AliceO2 or independent)
- get rid of as much boiler plate code as possible in the modules (typically the install function)
- add the o2_setup macro that modules should call (related to previous point?)
- standalone module example

There is also a new point to discuss : 
- GlobalTracking depends on Common. It uses o2_target_link_bucket but it still has to
  explicitely use include_directories(../../Common/include). Maybe it is ok, but I am not sure. 

Disconnecting now

**Comment by ktf** [comment]
For the record, you can use the syntax:
- [ ] This is a todo item not done
- [x] This is a todo item done

to keep track of todo items, without having to create real "issues".

**Comment by Barthelemy** [comment]
As there are no other comments , I will merge this PR and will carry on with the work on this.

**Pull request merged**
